// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAPhc5SNg1acyT_D_jo4edQD43PeR8GbZs",
      authDomain: "portfolio-c1274.firebaseapp.com",
      projectId: "portfolio-c1274",
      storageBucket: "portfolio-c1274.appspot.com",
      messagingSenderId: "40081637330",
      appId: "1:40081637330:web:5e49ab59e5f0755823120b");

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAPhc5SNg1acyT_D_jo4edQD43PeR8GbZs",
      authDomain: "portfolio-c1274.firebaseapp.com",
      projectId: "portfolio-c1274",
      storageBucket: "portfolio-c1274.appspot.com",
      messagingSenderId: "40081637330",
      appId: "1:40081637330:web:5e49ab59e5f0755823120b");

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyAPhc5SNg1acyT_D_jo4edQD43PeR8GbZs",
      authDomain: "portfolio-c1274.firebaseapp.com",
      projectId: "portfolio-c1274",
      storageBucket: "portfolio-c1274.appspot.com",
      messagingSenderId: "40081637330",
      appId: "1:40081637330:web:5e49ab59e5f0755823120b");

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyAPhc5SNg1acyT_D_jo4edQD43PeR8GbZs",
      authDomain: "portfolio-c1274.firebaseapp.com",
      projectId: "portfolio-c1274",
      storageBucket: "portfolio-c1274.appspot.com",
      messagingSenderId: "40081637330",
      appId: "1:40081637330:web:5e49ab59e5f0755823120b");

  static const FirebaseOptions windows = FirebaseOptions(
      apiKey: "AIzaSyAPhc5SNg1acyT_D_jo4edQD43PeR8GbZs",
      authDomain: "portfolio-c1274.firebaseapp.com",
      projectId: "portfolio-c1274",
      storageBucket: "portfolio-c1274.appspot.com",
      messagingSenderId: "40081637330",
      appId: "1:40081637330:web:5e49ab59e5f0755823120b");
}
